version: '3.1'

services:
  cve-1-joomla-before:
    image: joomla:3.8.0
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8081:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: admin

  cve-1-joomla-after:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8082:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: admin

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - "joomladb:mysql"
    ports:
      - "8083:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
      PMA_HOST: mysql