version: '3'
services:
    php-apache:
        image: df.ctu.univ-fcomte.fr/abachett-vuln1-unsafe-joomla_php-apache:latest
        ports:
            - 8081:80
        depends_on:
            - mariadb

    mariadb:
        image: df.ctu.univ-fcomte.fr/abachett-vuln1-unsafe-joomla_mariadb:latest
        expose:
            - 3306
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_USER: 'eaduser'
            MYSQL_PASSWORD: 'eadpassword'
            MYSQL_DATABASE: 'Joomla'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mariadb
        ports:
            - "8083:80"
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: toor
            PMA_HOST: mariadb
